"""A-REF fixture AUTHORING generator (one-time tool; NOT part of the conformance runtime).

Run once at fixture-authoring time to compute and store, for every catalog case:
  - tests/aref/expected/<fixture_id>.expected.json   (declared literals + authored disposition)
  - tests/aref/plan_artifacts/<fixture_id>.plan.json (the canonical raw plan artifact)
and to append an authoring log line.

This tool follows the R4F 9.10(a) role split: the plan is generated by the REAL planner over the
pre-state's real kernel report at authoring time; the ARTIFACTS are then predeclared inputs to
the conformance runtime (no runtime derivation; R4F 8.2/9.10).

Usage:  python -m tests.aref.authoring.generate_fixtures     (from the repository root)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from types import SimpleNamespace

from tests.aref.aref_harness import run_pure_case
from tests.aref.aref_fixture import validate_fixture
from tests.aref.aref_plan import (canonical_plan_bytes, construct_plan, plan_artifact_digest,
                                  plan_identity, plan_to_raw, real_merge_plan, real_plan,
                                  repoint_face_ids)
from tests.aref.aref_pure import make_pure_extractor
from tests.aref.fixtures import SPECS, load_case

AREF_DIR = Path(__file__).resolve().parent.parent
EXPECTED_DIR = AREF_DIR / "expected"
PLAN_DIR = AREF_DIR / "plan_artifacts"
LOG_PATH = AREF_DIR / "authoring_log.txt"


def _shim(spec: dict) -> SimpleNamespace:
    return SimpleNamespace(datablocks=spec["datablocks"], objects=spec["objects"], scene=spec["scene"])


def build_plan_artifact(spec: dict):
    """Generate the raw plan artifact exactly as the case's construction rule declares."""
    shim = _shim(spec)
    extractor = make_pure_extractor(shim)
    from tests.aref.aref_pure import build_graph
    graph = build_graph(shim)
    scene, report = extractor(graph)
    rule = spec["plan_construction"]["rule"]
    if rule == "PM":
        # the planner's explicit merge pass (the sole REPAIR_MERGE_VERTEX producer at the baseline)
        payload = graph.project_payload(spec["scene"]["scene_id"], spec["scene"]["unit_system"],
                                        spec["scene"].get("coordinate_frame"))
        outcome = real_merge_plan(report, payload)
        if outcome.refusal_code is not None:
            raise RuntimeError(f"merge pass refused: {outcome.refusal_code} ({outcome.refusal_detail})")
        plan = outcome.plan
        raw = plan_to_raw(plan)
        return plan, raw, scene, report
    plan = real_plan(report)
    if rule == "P1" and spec["plan_construction"].get("repoint"):
        fp = spec["plan_construction"]["repoint"]["face_ids"]
        dups = [c for c in plan.corrections if c.correction_type == spec["operation"]]
        if len(dups) != 1:
            raise RuntimeError(f"repoint base must be unique; found {len(dups)} corrections of the operation")
        base_pair = tuple(dups[0].parameters["face_ids"])
        plan = repoint_face_ids(plan, spec["operation"], base_pair, tuple(fp))
    else:
        plan = construct_plan(plan, rule, spec["operation"], spec["plan_construction"])
    raw = plan_to_raw(plan)
    return plan, raw, scene, report


def generate_case(fixture_id: str) -> str:
    spec = dict(SPECS[fixture_id])
    plan, raw, scene, report = build_plan_artifact(spec)
    from planning.blender.kernel import scene_input_digest

    ident = plan_identity(plan)
    expected = {
        "pre_digest": scene_input_digest(scene),
        "graph_witness": None,  # filled from the harness observation below
        "plan": {
            "artifact_sha256": plan_artifact_digest(raw),
            "plan_id": ident.plan_id,
            "source_report_digest": ident.source_report_digest,
            "correction_ids": list(ident.correction_ids),
        },
        "outcomes": {},
        "child_digest": None,
        "oc_class": "OC1",  # placeholder for the authoring observation run; overwritten below
        "disposition": "POSITIVELY_DEMONSTRATED",
    }
    # observe the case once (authoring observation) to fill the declared expectation.
    work = dict(spec)
    work["expected"] = expected
    # graph witness needs an initially filled object list; build it from the shim graph.
    from tests.aref.aref_harness import graph_witness
    from tests.aref.aref_pure import build_graph
    work["expected"]["graph_witness"] = graph_witness(build_graph(_shim(spec)))
    auth_literal = None
    observed = {"status": "observed"}

    if spec["params"] and len(ident.parameters) == 1:
        # declared params must agree with the real plan's recorded params (subset, key-wise)
        for k, v in spec["params"].items():
            if ident.parameters[0].get(k) != v:
                observed.setdefault("params_mismatch", {})[k] = {"declared": v, "plan": ident.parameters[0].get(k)}
    if spec["operation"] in ("REPAIR_FACE_WINDING", "REPAIR_MERGE_VERTEX") and not fixture_id.endswith("-AUTHREQ"):
        # An AMBIGUOUS plan is refused by the executor BEFORE the authorization gate, so an aliased
        # verbatim case reaches its OC1 refusal parity with NO authorization fixture at all. (An
        # AUTHORIZATION_REQUIRED (REVIEW_REQUIRED_NOT_AUTO) result is NOT this case: those fixtures
        # need a real authorization artifact to reach the mutator, so the search below still runs.)
        work["authorization_fixture"] = None
        try:
            probe_spec = validate_fixture(work)
            probe_run = run_pure_case(probe_spec, raw)
        except Exception as exc:  # noqa: BLE001 - authoring probe
            probe_run = None
            observed.setdefault("no_auth_probe_error", f"{type(exc).__name__}: {exc}")
        if (probe_run is not None
                and probe_run.receipt.get("failure_code") == "AMBIGUOUS_MULTIPLE_EXECUTABLE_CORRECTIONS"):
            expected["outcomes"] = {"pure": probe_run.receipt.get("result"), "live": None}
            expected["oc_class"] = probe_run.normal_form["oc_class"]
            expected["child_digest"] = probe_run.scene_digest_child
            observed = {"status": "observed", "result": probe_run.receipt.get("result"),
                        "failure_code": probe_run.receipt.get("failure_code"),
                        "oc_class": probe_run.normal_form["oc_class"],
                        "invocations": probe_run.normal_form["invocation_count"],
                        "note": "ambiguity refusal precedes the authorization gate; no auth fixture"}
            EXPECTED_DIR.mkdir(parents=True, exist_ok=True)
            PLAN_DIR.mkdir(parents=True, exist_ok=True)
            out = {"expected": expected, "authorization_fixture": None, "observed": observed}
            (EXPECTED_DIR / f"{fixture_id}.expected.json").write_text(
                json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            (PLAN_DIR / f"{fixture_id}.plan.json").write_text(
                json.dumps(raw, indent=1, sort_keys=True) + "\n", encoding="utf-8")
            return f"{fixture_id}: {observed}"
        candidate = _build_auth_candidates(spec, plan, ident)
        ok = None
        for variant in candidate:
            work["authorization_fixture"] = variant
            try:
                fspec = validate_fixture(work)
                run = run_pure_case(fspec, raw)
                if run.normal_form["invocation_count"] >= 1 or run.normal_form["oc_class"] == "OC1":
                    if run.normal_form["oc_class"] in ("OC2", "OC5", "OC6", "OC3"):
                        ok = (variant, run)
                        break
            except Exception as exc:  # noqa: BLE001 - authoring search
                observed.setdefault("auth_variant_errors", []).append(f"{type(exc).__name__}: {exc}")
        if ok is None:
            expected["disposition"] = "NOT_APPLICABLE"
            observed = {"status": "AUTH_VARIANT_UNAVAILABLE", "detail": observed}
        else:
            auth_literal, run = ok
            expected["outcomes"] = {"pure": run.receipt.get("result"), "live": None}
            expected["oc_class"] = run.normal_form["oc_class"]
            expected["child_digest"] = run.scene_digest_child
            observed = {"status": "observed", "result": run.receipt.get("result"),
                        "oc_class": run.normal_form["oc_class"],
                        "invocations": run.normal_form["invocation_count"]}
    else:
        work["authorization_fixture"] = None
        fspec = validate_fixture(work)
        run = run_pure_case(fspec, raw)
        expected["outcomes"] = {"pure": run.receipt.get("result"), "live": None}
        expected["oc_class"] = run.normal_form["oc_class"]
        expected["child_digest"] = run.scene_digest_child
        observed = {"status": "observed", "result": run.receipt.get("result"),
                    "failure_code": run.receipt.get("failure_code"),
                    "oc_class": run.normal_form["oc_class"],
                    "invocations": run.normal_form["invocation_count"]}

    EXPECTED_DIR.mkdir(parents=True, exist_ok=True)
    PLAN_DIR.mkdir(parents=True, exist_ok=True)
    out = {"expected": expected, "authorization_fixture": auth_literal, "observed": observed}
    (EXPECTED_DIR / f"{fixture_id}.expected.json").write_text(
        json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (PLAN_DIR / f"{fixture_id}.plan.json").write_text(
        json.dumps(raw, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    return f"{fixture_id}: {observed}"


def _build_auth_candidates(spec: dict, plan, ident):
    """Candidate authorization fixtures (marker in the permitted free-text field ONLY).

    The values are planner-derived literals computed at authoring time (R4F 8.2): plan_id,
    correction_id and source_report_digest are used verbatim; only authorized_by/scope_note carry
    the AREF-TEST- marker. Variants differ only in the optional designation fields, which the
    generator tries against the executor's binding logic and keeps the accepted one.
    """
    common = {
        "authorization_version": "1",
        "authorization_policy_version": "1",
        "decision": "APPROVED",
        "correction_type": spec["operation"],
        "correction_id": ident.correction_ids[0],
        "plan_id": ident.plan_id,
        "source_report_digest": ident.source_report_digest,
        "authorized_by": "AREF-TEST-fixture",
        "authorized_at_utc": "2026-10-08T00:00:00Z",
        "scope_note": f"AREF-TEST-{spec['fixture_id']}",
    }
    variants = []
    if spec["operation"] == "REPAIR_FACE_WINDING":
        base = dict(common)
        variants.append(base)  # D1 (artifact supplies no designation)
        d2 = dict(common)
        params = ident.parameters[0]
        pair = params.get("candidate_faces") or params.get("recorded_edges")
        cand = None
        if isinstance(pair, (list, tuple)) and pair:
            cand = pair[0] if isinstance(pair[0], int) else None
        if cand is None:
            cand = 0
        d2["designated_face_index"] = cand
        variants.append(d2)
    elif spec["operation"] == "REPAIR_MERGE_VERTEX":
        params = ident.parameters[0]
        common = dict(common)
        if params.get("mapping_digest"):
            common["expected_merge_mapping_digest"] = params["mapping_digest"]
        variants.append(common)
    return variants


def main() -> int:
    lines = []
    selected = sys.argv[1:] or sorted(SPECS)
    for fixture_id in selected:
        try:
            lines.append(generate_case(fixture_id))
        except Exception as exc:  # noqa: BLE001 - authoring tool reports and continues
            lines.append(f"{fixture_id}: ERROR {type(exc).__name__}: {exc}")
    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write("\n--- authoring run ---\n")
        for line in lines:
            fh.write(line + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
