"""A-REF plan artifact module: P1/P2/P3 construction, canonical serialization, identity binding.

Design authority: R4F section 9.10 (plan provenance, construction rules, shared artifact,
ownership), 16.2 (duplicate cases), 25 (fixture plan rules).

The plan is generated by the REAL planner and consumed by the EXISTING executor. This module
reproduces the pinned driver's documented construction patterns exactly:
  P2 selected_pair  — w1_w1b_face_removal_live_script.py:575-588;
  P3 keep_only_target — w1_w1b_face_removal_live_script.py:332-346;
  re-point (16.2(b)) — remap_plan semantics, :319-345.
No plan field is hand-forged; plan_id is recomputed by the CorrectionPlan contract
(correction_contract.py:242-252).
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

from planning.blender.correction_contract import CorrectionPlan, CorrectionProposal
from planning.blender.correction_planner import PLANNER_VERSION, _correction_id, plan_scene_report
from planning.blender.correction_values import thaw_jsonable
from planning.blender.finding_codes import FindingCode
from planning.blender.scene_report import REPORT_FORMAT_VERSION

#: Language-neutral planner profile (same literal the pinned driver uses, w1 :85-86).
PLANNER_PROFILE = {
    "name": "soccer-field",
    "version": "1",
    "allowed_units": ["METERS", "meters", "m"],
    "name_pattern": r"^[a-z0-9][a-z0-9._-]*$",
}


class BindingError(Exception):
    """A pre-mutation binding check failed: FIXTURE-BINDING-MISMATCH (R4F 24 step 6; G36).

    Fail closed: NO mutation is permitted on either path; the case records no semantic verdict.
    The harness re-exports this class; plan-layer failures raise the subclass PlanBindingError.
    """


class PlanBindingError(BindingError):
    """A plan-artifact identity check failed (fail closed BEFORE mutation; R4F 9.10(e), G36)."""


def report_dict(report: Any) -> Dict[str, Any]:
    """The established planner input form (w1 :307-312)."""
    payload = report.to_json_compatible()
    payload["digest"] = report.digest()
    payload["report_format_version"] = REPORT_FORMAT_VERSION
    return payload


def real_plan(report: Any) -> CorrectionPlan:
    """The REAL planner over the REAL kernel report (single generation; R4F 9.10(a))."""
    return plan_scene_report(report_dict(report), profile=PLANNER_PROFILE)


def _correction_to_raw(c: CorrectionProposal) -> Dict[str, Any]:
    return {
        "correction_id": c.correction_id,
        "finding_code": c.finding_code,
        "object_id": c.object_id,
        "mesh_id": c.mesh_id,
        "correction_type": c.correction_type,
        "parameters": thaw_jsonable(c.parameters),
        "rationale": c.rationale,
        "preconditions": [thaw_jsonable(p) for p in c.preconditions],
        "expected_postcondition": thaw_jsonable(c.expected_postcondition),
        "risk": c.risk,
        "severity": c.severity,
        "reversibility": c.reversibility,
        "dependencies": list(c.dependencies),
        "determinism": c.determinism,
        "requires_human_review": c.requires_human_review,
        "out_of_scope": c.out_of_scope,
    }


def plan_to_raw(plan: CorrectionPlan) -> Dict[str, Any]:
    """Serialize a plan field-wise into the raw mapping consumed by the EXISTING
    reconstruction contract (correction_execution_bridge_runtime.py:68-116; R4F 9.10(d))."""
    return {
        "plan_id": plan.plan_id,
        "source_report_digest": plan.source_report_digest,
        "source_revision_id": plan.source_revision_id,
        "planner_version": plan.planner_version,
        "profile": thaw_jsonable(plan.profile),
        "corrections": [_correction_to_raw(c) for c in plan.corrections],
        "dependencies": [list(edge) for edge in plan.dependencies],
        "summary_metrics": thaw_jsonable(plan.summary_metrics),
        "state": thaw_jsonable(plan.state),
        "planning_errors": list(plan.planning_errors),
    }


def canonical_plan_bytes(raw: Dict[str, Any]) -> bytes:
    """Canonical artifact bytes: sorted keys, compact separators, ASCII-escaped (R4F 9.10(d))."""
    return json.dumps(raw, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")


def plan_artifact_digest(raw: Dict[str, Any]) -> str:
    return hashlib.sha256(canonical_plan_bytes(raw)).hexdigest()


def raw_to_plan(raw: Dict[str, Any]) -> CorrectionPlan:
    """Reconstruct the plan from the canonical raw mapping (no new format; R4F 9.10(d)).

    The production reconstruction contract lives in the bridge runtime, which imports ``bpy`` at
    module level and is therefore unavailable on the headless pure path. This function mirrors the
    RUNTIME contract FIELD-FOR-FIELD (correction_execution_bridge_runtime.py:68-116): identical
    accessor treatment for all 16 CorrectionProposal and 10 CorrectionPlan fields, identical
    .get-with-default form, and only the raised type differs (PlanBindingError vs BridgeRuntimeError).
    LIMITATION (stated, not hidden): cross-process equivalence against the bridge's own function is
    NOT machine-asserted here — the module cannot be imported headless (bpy at module level). The
    static field comparison is the available evidence; a live equivalence test would require the
    Blender-enabled second slice.
    """
    if type(raw) is not dict:
        raise PlanBindingError("raw plan must be an exact dict")
    corrections = []
    for item in raw.get("corrections", []):
        corrections.append(CorrectionProposal(
            correction_id=item["correction_id"],
            finding_code=item["finding_code"],
            object_id=item.get("object_id"),
            mesh_id=item.get("mesh_id"),
            correction_type=item["correction_type"],
            parameters=item["parameters"],
            rationale=item["rationale"],
            preconditions=tuple(item.get("preconditions", [])),
            expected_postcondition=item["expected_postcondition"],
            risk=item["risk"],
            severity=item["severity"],
            reversibility=item["reversibility"],
            dependencies=tuple(item.get("dependencies", [])),
            determinism=item["determinism"],
            requires_human_review=item["requires_human_review"],
            out_of_scope=item["out_of_scope"],
        ))
    return CorrectionPlan(
        plan_id=raw["plan_id"],
        source_report_digest=raw["source_report_digest"],
        source_revision_id=raw.get("source_revision_id"),
        planner_version=raw["planner_version"],
        profile=raw["profile"],
        corrections=tuple(corrections),
        dependencies=tuple(tuple(edge) for edge in raw.get("dependencies", [])),
        summary_metrics=raw["summary_metrics"],
        state=raw["state"],
        planning_errors=tuple(raw.get("planning_errors", [])),
    )


def _reduced_plan(plan: CorrectionPlan, corrections: Tuple[CorrectionProposal, ...], *,
                  source_revision_id: Any, planner_version: str, profile: Any) -> CorrectionPlan:
    """Build a reduced plan mirroring the pinned driver's constructions EXACTLY.

    w1 :582-588 (selected_pair) copies the planner's source_revision_id /
    planner_version / profile; w1 :332-346 (keep_only_target) sets
    source_revision_id=None and planner_version="1" as literals. Plan_id stays ""
    here: the CorrectionPlan contract recomputes it (self-committing; correction_contract.py:242-252).
    """
    return CorrectionPlan(
        plan_id="",
        source_report_digest=plan.source_report_digest,
        source_revision_id=source_revision_id,
        planner_version=planner_version,
        profile=profile,
        corrections=tuple(corrections),
        dependencies=(),
        summary_metrics=thaw_jsonable(plan.summary_metrics),
        state=plan.state,
        planning_errors=tuple(plan.planning_errors),
    )


def select_pair(plan: CorrectionPlan, operation: str, pair: Tuple[int, int]) -> CorrectionPlan:
    """P2: the pinned `selected_pair` selection (w1 :575-588). The executor never chooses."""
    matches = [c for c in plan.corrections
               if c.correction_type == operation and tuple(c.parameters["face_ids"]) == tuple(pair)]
    if len(matches) != 1:
        raise PlanBindingError(f"fixture pair {pair!r} not unique in the planner output: {len(matches)} matches")
    return _reduced_plan(plan, tuple(matches),
                         source_revision_id=plan.source_revision_id,
                         planner_version=plan.planner_version,
                         profile=thaw_jsonable(plan.profile))


def keep_only_target(plan: CorrectionPlan, operation: str, mesh_ids: Tuple[str, ...]) -> CorrectionPlan:
    """P3: the pinned `keep_only_target` reduction (w1 :332-346), literals included (R4F K2)."""
    kept = tuple(c for c in plan.corrections
                 if c.correction_type == operation and c.mesh_id in mesh_ids)
    if not kept:
        raise PlanBindingError(f"keep_only_target left no correction for {operation!r} on {mesh_ids!r}")
    return _reduced_plan(plan, kept, source_revision_id=None, planner_version=PLANNER_VERSION,
                         profile=thaw_jsonable(plan.profile))


def repoint_face_ids(plan: CorrectionPlan, operation: str, pair: Tuple[int, int],
                     new_pair: Tuple[int, int]) -> CorrectionPlan:
    """The 16.2(b) documented parameter re-point: only the recorded face_ids change; the
    correction id is recomputed with the planner's own content-addressed helper (w1 :319-345)."""
    base = [c for c in plan.corrections
            if c.correction_type == operation and tuple(c.parameters["face_ids"]) == tuple(pair)]
    if len(base) != 1:
        raise PlanBindingError(f"re-point base pair {pair!r} not unique: {len(base)} matches")
    c = base[0]
    params = dict(thaw_jsonable(c.parameters))
    params["face_ids"] = [int(new_pair[0]), int(new_pair[1])]
    rebuilt = CorrectionProposal(
        correction_id=_correction_id(FindingCode(c.finding_code), c.object_id, c.mesh_id, params),
        finding_code=c.finding_code, object_id=c.object_id, mesh_id=c.mesh_id,
        correction_type=c.correction_type, parameters=params, rationale=c.rationale,
        preconditions=tuple(thaw_jsonable(c.preconditions)),
        expected_postcondition=thaw_jsonable(c.expected_postcondition),
        risk=c.risk, severity=c.severity, reversibility=c.reversibility,
        dependencies=tuple(c.dependencies), determinism=c.determinism,
        requires_human_review=c.requires_human_review, out_of_scope=c.out_of_scope)
    return _reduced_plan(plan, (rebuilt,), source_revision_id=plan.source_revision_id,
                         planner_version=plan.planner_version, profile=thaw_jsonable(plan.profile))


def construct_plan(plan: CorrectionPlan, rule: str, operation: str, pc: Dict[str, Any]) -> CorrectionPlan:
    """Apply the fixture-declared construction rule (P1/P2/P3) to the real planner output."""
    if rule == "P1":
        return plan
    if rule == "P2":
        return select_pair(plan, operation, tuple(pc["selected_pair"]))
    if rule == "P3":
        return keep_only_target(plan, operation, tuple(pc["keep_only_target"]))
    raise PlanBindingError(f"unsupported construction rule {rule!r}")


@dataclass
class PlanIdentity:
    plan_id: str
    source_report_digest: str
    correction_ids: List[str]
    parameters: List[Dict[str, Any]]


def plan_identity(plan: CorrectionPlan) -> PlanIdentity:
    return PlanIdentity(
        plan_id=plan.plan_id,
        source_report_digest=plan.source_report_digest,
        correction_ids=[c.correction_id for c in plan.corrections],
        parameters=[thaw_jsonable(c.parameters) for c in plan.corrections],
    )


def check_plan_binding(plan: CorrectionPlan, raw: Dict[str, Any],
                       expected_plan: Dict[str, Any]) -> Dict[str, Any]:
    """The step-6 plan-identity binding (R4F 9.10(e), 24 step 6). Fails closed on any mismatch.

    Verifies: artifact digest == spec literal; plan_id == spec literal; source_report_digest ==
    spec literal; correction ids == spec literals. (The executor revalidates plan_id itself;
    G36/G45.)
    """
    digest = plan_artifact_digest(raw)
    ident = plan_identity(plan)
    checks = {
        "artifact_sha256": digest,
        "plan_id": ident.plan_id,
        "source_report_digest": ident.source_report_digest,
        "correction_ids": ident.correction_ids,
    }
    if digest != expected_plan["artifact_sha256"]:
        raise PlanBindingError(f"plan artifact digest {digest} != declared {expected_plan['artifact_sha256']}")
    if ident.plan_id != expected_plan["plan_id"]:
        raise PlanBindingError(f"plan_id {ident.plan_id} != declared {expected_plan['plan_id']}")
    if ident.source_report_digest != expected_plan["source_report_digest"]:
        raise PlanBindingError("source_report_digest mismatch vs declared literal")
    if list(ident.correction_ids) != list(expected_plan["correction_ids"]):
        raise PlanBindingError(
            f"correction ids {ident.correction_ids} != declared {expected_plan['correction_ids']}")
    return checks


# ---------------------------------------------------------------------------------------------
# C4 merge planning (R4F 16.6(1) "each fixture declares its construction rule").
#
# The planner's AUTOMATIC pass deliberately emits no merge proposal (correction_planner.py:687-694:
# the mapping row keeps auto_propose=False); ``plan_merge_vertex_correction`` is the ONLY producer
# of a REPAIR_MERGE_VERTEX correction and is the planner's explicit-operator-request entry point.
# The C4 fixture therefore declares the construction rule "PM" (planner merge pass) and BOTH paths
# invoke that same real-planner entry point over their own independently derived report.
# ---------------------------------------------------------------------------------------------

def report_dict(report: Any) -> Dict[str, Any]:
    """The SceneReport-shaped dict the merge pass consumes (same form the pinned driver builds)."""
    payload = report.to_json_compatible()
    payload["digest"] = report.digest()
    payload["report_format_version"] = REPORT_FORMAT_VERSION
    return payload


def scene_input_dict(payload: Dict[str, Any]) -> Dict[str, Any]:
    """The SCENE-INPUT grammar for the real planner (no extraction-only schema_version field)."""
    out = dict(payload)
    out.pop("schema_version", None)
    return out


def real_merge_plan(report: Any, payload: Dict[str, Any]) -> Any:
    """Run the REAL planner's explicit merge pass (the sole merge producer) over one report."""
    from planning.blender.correction_planner import plan_merge_vertex_correction

    return plan_merge_vertex_correction(report_dict(report), scene_input_dict(payload),
                                        profile=PLANNER_PROFILE)
